title: Sigit Purnomo
url: "https://sigit-purnomo.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "#"
 - name: "Resume"
   link: "#"
 - name: "Contact"
   link: "#"
